declare module 'lucide-react' {
    import * as React from 'react';

    export interface LucideProps extends React.SVGProps<SVGSVGElement> {
        color?: string;
        size?: string | number;
        absoluteStrokeWidth?: boolean;
    }

    export type LucideIcon = React.ForwardRefExoticComponent<
        LucideProps & React.RefAttributes<SVGSVGElement>
    >;

    export const Activity: LucideIcon;
    export const AlertCircle: LucideIcon;
    export const AlertCircleIcon: LucideIcon;
    export const AlertTriangle: LucideIcon;
    export const ArrowDownUp: LucideIcon;
    export const ArrowLeftRight: LucideIcon;
    export const ArrowUpDown: LucideIcon;
    export const BarChart: LucideIcon;
    export const Barcode: LucideIcon;
    export const Book: LucideIcon;
    export const BookOpen: LucideIcon;
    export const Box: LucideIcon;
    export const Briefcase: LucideIcon;
    export const Building2: LucideIcon;
    export const Calculator: LucideIcon;
    export const Calendar: LucideIcon;
    export const CalendarDays: LucideIcon;
    export const CalendarIcon: LucideIcon;
    export const Check: LucideIcon;
    export const CheckCircle2: LucideIcon;
    export const CheckIcon: LucideIcon;
    export const CheckSquare: LucideIcon;
    export const ChevronDown: LucideIcon;
    export const ChevronDownIcon: LucideIcon;
    export const ChevronLeftIcon: LucideIcon;
    export const ChevronRight: LucideIcon;
    export const ChevronRightIcon: LucideIcon;
    export const ChevronUpIcon: LucideIcon;
    export const ChevronsUpDown: LucideIcon;
    export const CircleDollarSign: LucideIcon;
    export const CircleIcon: LucideIcon;
    export const ClipboardCheck: LucideIcon;
    export const Clock: LucideIcon;
    export const Copy: LucideIcon;
    export const Database: LucideIcon;
    export const Download: LucideIcon;
    export const Edit: LucideIcon;
    export const Eye: LucideIcon;
    export const EyeOff: LucideIcon;
    export const FileText: LucideIcon;
    export const Filter: LucideIcon;
    export const Folder: LucideIcon;
    export const FolderTree: LucideIcon;
    export const GitBranch: LucideIcon;
    export const Globe: LucideIcon;
    export const Hash: LucideIcon;
    export const History: LucideIcon;
    export const IdCard: LucideIcon;
    export const Info: LucideIcon;
    export const Layers: LucideIcon;
    export const LayoutGrid: LucideIcon;
    export const LayoutList: LucideIcon;
    export const Library: LucideIcon;
    export const Link: LucideIcon;
    export const List: LucideIcon;
    export const Loader2: LucideIcon;
    export const LoaderCircle: LucideIcon;
    export const LockKeyhole: LucideIcon;
    export const Lock: LucideIcon;
    export const LogOut: LucideIcon;
    export const Map: LucideIcon;
    export const MapPin: LucideIcon;
    export const Minus: LucideIcon;
    export const Monitor: LucideIcon;
    export const Moon: LucideIcon;
    export const Menu: LucideIcon;
    export const MoreHorizontal: LucideIcon;
    export const MoreHorizontalIcon: LucideIcon;
    export const Package: LucideIcon;
    export const PanelLeftIcon: LucideIcon;
    export const Pencil: LucideIcon;
    export const PieChart: LucideIcon;
    export const Plus: LucideIcon;
    export const PlusCircle: LucideIcon;
    export const Printer: LucideIcon;
    export const RefreshCw: LucideIcon;
    export const Ruler: LucideIcon;
    export const ScanLine: LucideIcon;
    export const Scale: LucideIcon;
    export const Search: LucideIcon;
    export const Settings: LucideIcon;
    export const Settings2: LucideIcon;
    export const Shield: LucideIcon;
    export const ShieldBan: LucideIcon;
    export const ShieldCheck: LucideIcon;
    export const ShoppingCart: LucideIcon;
    export const Sun: LucideIcon;
    export const Tags: LucideIcon;
    export const TrendingDown: LucideIcon;
    export const TrendingUp: LucideIcon;
    export const Trash: LucideIcon;
    export const Trash2: LucideIcon;
    export const Truck: LucideIcon;
    export const User: LucideIcon;
    export const UserCircle: LucideIcon;
    export const Users: LucideIcon;
    export const Wrench: LucideIcon;
    export const X: LucideIcon;
    export const XIcon: LucideIcon;
    export const Zap: LucideIcon;
}
